In [168]:
search_movie = TfidfVectorizer(stop_words=set(stopwords.words('english')),analyzer= 'word')
recommend_movie = TfidfVectorizer(stop_words=set(stopwords.words('english')),max_df=0.9,analyzer= 'word')

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.neighbors import NearestNeighbors
%matplotlib inline
import nltk
from nltk.corpus import stopwords
import plotly.graph_objs as go
from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.plotly as py
from gensim.summarization.bm25 import get_bm25_weights
from gensim.summarization.bm25 import BM25

In [172]:
recommend_movie = recommend_movie.fit(r_movie)

In [171]:
recommend_movie

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.9, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words={'for', 'couldn', 't', 'my', 'herself', 'mustn', 'of', 'any', "you'd", 'same', "that'll", 'haven', "mustn't", 'has', 've', 'very', 'because', 'isn', 'other', 'under', 'an', "mightn't", 'them', 'your', 'out', 'where', 'd', 'with', 'i', 'what', "you'll", "she's", "hasn't", 'above', 'be', 'a... 'between', 'itself', 'does', 'myself', 'now', 'himself', 'most', "haven't", 'shan', 'am', "hadn't"},
        strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [206]:
que_m = recommend_movie.transform(['lol']) 
# knn1 = NearestNeighbors(5,metric='cosine')
# knn1.fit(data_m)
result = knn.kneighbors(que_m)
labels = []
idx = []
for i in result[1][0]:
    j = np.argwhere(result[1][0] == i)[0][0]
    if(result[0][0][j] != 1):
        print('This is for review ' + str(i) + " : \n" + data_movie.iloc[i],'\n')
for i in result[1][0]:
    t = movie.iloc[i]['Title']
    if(pd.isna(t)):
        continue
    else:
        j = np.argwhere(result[1][0] == i)[0][0]
        if(int(result[0][0][j]) == 1):
            continue
        else:
            l = [t,data_movie.iloc[i]]
#             info.append([movie['scores'].iloc[i],movie['Genre'].iloc[i],l,movie['url'].iloc[i]])
            idx.append(j)
            labels.append(t)
values = (result[0][0])[idx]
colors = ['#FEBFB3', '#E1396C', '#96D38C', '#D0F9B1']
trace = go.Pie(labels=labels, values=values,
               hoverinfo='label+percent', textinfo='value', 
               textfont=dict(size=20),
               marker=dict(colors=colors, 
                           line=dict(color='#000000', width=2)))

py.iplot([trace], filename='styled_pie_chart')

This is for review 7642 : 
Miley Cyrus  Demi Moore  Ashley Greene  Douglas Booth  Adam G. Sevani  Thomas Jane  An authentic story that perfectly captures coming of age in today's digital world, LOL is a remake of the hugely popular 2008 French film LOL (Laughing Out Loud). Starting a new year of high school, Lola (Miley Cyrus), (or "Lol," as her friends call her), works to find the right balance between family, school, friends and romance. Broken-hearted by her ex, Lol's world is soon turned upside down when she is surprised to find her best friend, Kyle (Douglas Booth), a musician in an up and coming rock band, could possibly be the love of her life. In her quest towards independence, self-identity and young adulthood, Lol discovers that while Facebook "status" is easy to change; true relationships are worth the effort. -- (C) Lionsgate  Liza Azuelos  Lisa Azuelos    Lionsgate Films  LOL  Liza Azuelos  Lisa Azuelos  Karim Anouz    Comedy   



In [204]:
result[0][0][4] == 1

True

In [209]:
labels

['LOL  ']

In [196]:
labels

['LOL  ']

In [114]:
result = np.array(model_recom.get_scores('Brendan Fraser, John Hannah  '))
result_order = np.argsort(result)[::-1][:5]
labels = []
idx = []
for i in result_order:
    print('This is for review ' + str(i) + " : \n" + data_movie.iloc[i],'\n')
for i in result_order:
    t = movie.iloc[i]['Title']
    if(pd.isna(t)):
        continue
    else:
        labels.append(t)
        print("This is the title of the recommended movie " + t)

This is for review 14265 : 
Michael Biehn  Alexandra Daddario  Kathryn Meisle  Nolan Gerard Funk  Brett Rickaby  Spencer List  n 1989, six year old Martin Bristoll was kidnapped from his backyard swing in Minersville Pennsylvania. Graham Sutter, a psychotic recluse, kept Martin imprisoned on his derelict pig farm, forcing him to witness and participate in unspeakable horrors. Chosen at random, his victim's screams were drowned out by the rural countryside. For five years, Martin's whereabouts have remained a mystery, until 17 year old Allison Miller (Alexandra Daddario) comes to live with her Uncle, Jonathan (Michael Biehn). While exploring her new surroundings, Allison discovers things aren't quite right at the farmhouse down the road. Her curiosity disturbs a hornet's nest of evil and despair that once torn open, can never be closed. -- (C) Official Site  Stevan Mena      Crimson Films  Bereavement  Stevan Mena        Horror   

This is for review 8934 : 
Alice Cooper  Shep Gordon  D

In [85]:
result_order

array([12917,  5073,  4114,  5077, 12350])

In [184]:
data_m = vector_movie.fit_transform(s_movie)
que_m = vector_movie.transform(['lol']) 
knn = NearestNeighbors(10,metric='cosine')
knn.fit(data_m)
result = knn
labels = []
idx = []
for i in result[1][0]:
    print('This is for review ' + str(i) + " : \n" + data_movie.iloc[i],'\n')
for i in result[1][0]:
    t = movie.iloc[i]['Title']
    if(pd.isna(t)):
        continue
    else:
        j = np.argwhere(result[1][0] == i)[0][0]
        idx.append(j)
        labels.append(t)
        print("This is the title of the recommended movie " + t)
values = (result[0][0])[idx]
colors = ['#FEBFB3', '#E1396C', '#96D38C', '#D0F9B1']
trace = go.Pie(labels=labels, values=values,
               hoverinfo='label+percent', textinfo='value', 
               textfont=dict(size=20),
               marker=dict(colors=colors, 
                           line=dict(color='#000000', width=2)))

py.iplot([trace], filename='styled_pie_chart')

NameError: name 'vector_movie' is not defined

In [183]:
result[0][0]

array([0.76478331, 0.87635777, 0.88448803, 0.913603  , 0.91427124])

# idea

## We first display the result with any bias (do not refer to any other, if they like, great, if not, we should then ask further, content collabrative filtering), we can also give a general idea for different categories and some interesting facts, produce some graphs as well

# Tasks: 

In [144]:
import pickle

In [175]:
pickle.dump(recommend_movie, open('model_recommend.pkl','wb'))
pickle.dump(knn1, open('model.pkl','wb'))

In [ ]:
model = pickle.load(open('model.pkl','rb'))


In [147]:
data_m

<15085x29 sparse matrix of type '<class 'numpy.float64'>'
	with 437465 stored elements in Compressed Sparse Row format>

In [176]:
knn.kneighbors(que_m)[1][0]

array([ 3180,  1374, 12566,    67,  6557])

In [ ]:
movie1 = pd.read_csv('data/all_movie.csv')

In [ ]:
result = get_bm25_weights(s_movie, n_jobs=-1)

In [ ]:
result

In [53]:
import pickle
model_file = open('model.pkl','wb')

In [ ]:
get_bm25_weights(s_movie,n_jobs=-1)

In [54]:
pickle.dump(model,model_file)

In [ ]:
movie.iloc[[1,2,3]]

In [17]:
def clean(x):
    if(pd.isna(x)):
        return x
    if(x[:3] == 'nan'):
        return x[3:]
    return x
movie['Genre'] = movie['Genre'].apply(clean)

In [22]:
movie['Genre'] = movie['Genre'].fillna('Not Specified')

In [40]:
movie = movie[-pd.isna(movie.Description)]

In [46]:
movie = movie.drop(movie.columns[:3],axis = 1)

In [48]:
movie.to_csv('movie.csv',index = False)

In [ ]:
model = BM25(s_movie)

array(['Brendan Fraser  ', 'John Hannah  ', 'Maria Bello  ',
       'Michelle Yeoh  ', 'Jet Li  ', 'Russell Wong  ', 'Rob Cohen  ',
       'Simon Duggan  ', '  ', 'Universal Pictures  ',
       'The Mummy: Tomb of the Dragon Emperor  ', 'Alfred Gough  ',
       'Miles Millar  ', '  ', '  ', 'Action  Drama  Comedy  ', 5.2],
      dtype=object)

In [119]:
r_movie[0]

['Brendan',
 'Fraser',
 'John',
 'Hannah',
 'Maria',
 'Bello',
 'Michelle',
 'Yeoh',
 'Jet',
 'Li',
 'Russell',
 'Wong',
 'The',
 'Fast',
 'and',
 'the',
 'Furious',
 'director',
 'Rob',
 'Cohen',
 'continues',
 'the',
 'tale',
 'set',
 'into',
 'motion',
 'by',
 'director',
 'Stephen',
 'Sommers',
 'with',
 'this',
 'globe-trotting',
 'adventure',
 'that',
 'finds',
 'explorer',
 'Rick',
 "O'Connell",
 'and',
 'son',
 'attempting',
 'to',
 'thwart',
 'a',
 'resurrected',
 "emperor's",
 '(Jet',
 'Li)',
 'plan',
 'to',
 'enslave',
 'the',
 'entire',
 'human',
 'race.',
 "It's",
 'been',
 '2,000',
 'years',
 'since',
 "China's",
 'merciless',
 'Emperor',
 'Han',
 'and',
 'his',
 'formidable',
 'army',
 'were',
 'entombed',
 'in',
 'terra',
 'cotta',
 'clay',
 'by',
 'a',
 'double-dealing',
 'sorceress',
 '(Michelle',
 'Yeoh),',
 'but',
 'now,',
 'after',
 'centuries',
 'in',
 'suspended',
 'animation,',
 'an',
 'ancient',
 'curse',
 'is',
 'about',
 'to',
 'be',
 'broken.',
 'Thanks',
 '